
// Generated by Cadence Genus(TM) Synthesis Solution 16.22-s033_1
// Generated on: Apr 20 2020 12:23:50 EDT (Apr 20 2020 16:23:50 UTC)

// Verification Directory fv/ttlock_wrapper_WKEY8_WINPUT18 

module DUTLock(other_in, protected_in, out);
  input [9:0] other_in;
  input [7:0] protected_in;
  output out;
  wire [9:0] other_in;
  wire [7:0] protected_in;
  wire out;
  wire f_out, \genblk1.dut_N118 , \genblk1.dut_N122 , \genblk1.dut_N126
       , \genblk1.dut_N130 , \genblk1.dut_N134 , \genblk1.dut_N138 ,
       \genblk1.dut_N142 ;
  wire \genblk1.dut_N146 , \genblk1.dut_N150 , \genblk1.dut_N154 ,
       \genblk1.dut_N159 , \genblk1.dut_N162 , \genblk1.dut_N165 ,
       \genblk1.dut_N168 , \genblk1.dut_N171 ;
  wire \genblk1.dut_N174 , \genblk1.dut_N177 , \genblk1.dut_N180 ,
       \genblk1.dut_N199 , \genblk1.dut_n_44 , \genblk1.dut_n_45 ,
       \genblk1.dut_n_46 , \genblk1.dut_n_47 ;
  wire n_19, n_32, n_36, n_37, n_38;
  xor g1 (out, n_19, f_out);
  nand g10 (n_38, protected_in[0], protected_in[1], \genblk1.dut_N122 ,
       n_32);
  nand g11 (n_37, protected_in[4], protected_in[5], \genblk1.dut_N130 ,
       n_36);
  nor g12 (n_19, n_37, n_38);
  not g13 (n_36, protected_in[7]);
  not g14 (n_32, protected_in[3]);
  nand \genblk1.dut_NAND2_19  (\genblk1.dut_N154 , \genblk1.dut_N118 ,
       protected_in[1]);
  nand \genblk1.dut_NAND2_22  (\genblk1.dut_N159 , \genblk1.dut_N122 ,
       protected_in[3]);
  nand \genblk1.dut_NAND2_23  (\genblk1.dut_N162 , \genblk1.dut_N126 ,
       protected_in[5]);
  nand \genblk1.dut_NAND2_24  (\genblk1.dut_N165 , \genblk1.dut_N130 ,
       protected_in[7]);
  nand \genblk1.dut_NAND2_25  (\genblk1.dut_N168 , \genblk1.dut_N134 ,
       other_in[1]);
  nand \genblk1.dut_NAND2_26  (\genblk1.dut_N171 , \genblk1.dut_N138 ,
       other_in[3]);
  nand \genblk1.dut_NAND2_27  (\genblk1.dut_N174 , \genblk1.dut_N142 ,
       other_in[5]);
  nand \genblk1.dut_NAND2_28  (\genblk1.dut_N177 , \genblk1.dut_N146 ,
       other_in[7]);
  nand \genblk1.dut_NAND2_29  (\genblk1.dut_N180 , \genblk1.dut_N150 ,
       other_in[9]);
  not \genblk1.dut_NOT1_1  (\genblk1.dut_N118 , protected_in[0]);
  not \genblk1.dut_NOT1_3  (\genblk1.dut_N122 , protected_in[2]);
  not \genblk1.dut_NOT1_5  (\genblk1.dut_N126 , protected_in[4]);
  not \genblk1.dut_NOT1_7  (\genblk1.dut_N130 , protected_in[6]);
  not \genblk1.dut_NOT1_9  (\genblk1.dut_N134 , other_in[0]);
  not \genblk1.dut_NOT1_11  (\genblk1.dut_N138 , other_in[2]);
  not \genblk1.dut_NOT1_13  (\genblk1.dut_N142 , other_in[4]);
  not \genblk1.dut_NOT1_15  (\genblk1.dut_N146 , other_in[6]);
  not \genblk1.dut_NOT1_17  (\genblk1.dut_N150 , other_in[8]);
  not \genblk1.dut_NOT1_47  (f_out, \genblk1.dut_N199 );
  and \genblk1.dut_g1  (\genblk1.dut_n_44 , \genblk1.dut_N154 ,
       \genblk1.dut_N159 , \genblk1.dut_N162 );
  and \genblk1.dut_g2  (\genblk1.dut_n_45 , \genblk1.dut_N165 ,
       \genblk1.dut_N168 );
  and \genblk1.dut_g3  (\genblk1.dut_n_46 , \genblk1.dut_N171 ,
       \genblk1.dut_N174 );
  and \genblk1.dut_g4  (\genblk1.dut_n_47 , \genblk1.dut_N177 ,
       \genblk1.dut_N180 );
  and \genblk1.dut_g5  (\genblk1.dut_N199 , \genblk1.dut_n_44 ,
       \genblk1.dut_n_45 , \genblk1.dut_n_46 , \genblk1.dut_n_47 );
endmodule

