
// Generated by Cadence Genus(TM) Synthesis Solution 16.22-s033_1
// Generated on: Apr 20 2020 12:23:15 EDT (Apr 20 2020 16:23:15 UTC)

// Verification Directory fv/ttlock_wrapper_WKEY16_WINPUT18 

module DUTLock(other_in, protected_in, out);
  input [1:0] other_in;
  input [15:0] protected_in;
  output out;
  wire [1:0] other_in;
  wire [15:0] protected_in;
  wire out;
  wire f_out, \genblk1.dut_N118 , \genblk1.dut_N122 , \genblk1.dut_N126
       , \genblk1.dut_N130 , \genblk1.dut_N134 , \genblk1.dut_N138 ,
       \genblk1.dut_N142 ;
  wire \genblk1.dut_N146 , \genblk1.dut_N150 , \genblk1.dut_N154 ,
       \genblk1.dut_N159 , \genblk1.dut_N162 , \genblk1.dut_N165 ,
       \genblk1.dut_N168 , \genblk1.dut_N171 ;
  wire \genblk1.dut_N174 , \genblk1.dut_N177 , \genblk1.dut_N180 ,
       \genblk1.dut_N199 , \genblk1.dut_n_44 , \genblk1.dut_n_45 ,
       \genblk1.dut_n_46 , \genblk1.dut_n_47 ;
  wire n_19, n_37, n_38, n_39, n_40, n_41, n_42, n_43;
  wire n_44, n_45, n_46, n_47, n_48, n_49, n_50, n_51;
  wire n_52, n_53, n_54, n_55, n_56;
  xor g1 (out, n_19, f_out);
  xnor g2 (n_37, protected_in[0], 1'b0);
  xnor g3 (n_38, protected_in[1], 1'b1);
  xnor g4 (n_39, protected_in[2], 1'b1);
  xnor g5 (n_40, protected_in[3], 1'b0);
  xnor g6 (n_41, protected_in[4], 1'b1);
  xnor g7 (n_42, protected_in[5], 1'b1);
  xnor g8 (n_43, protected_in[6], 1'b1);
  xnor g9 (n_44, protected_in[7], 1'b1);
  xnor g10 (n_45, protected_in[8], 1'b1);
  xnor g11 (n_46, protected_in[9], 1'b1);
  xnor g12 (n_47, protected_in[10], 1'b0);
  xnor g13 (n_48, protected_in[11], 1'b1);
  xnor g14 (n_49, protected_in[12], 1'b1);
  xnor g15 (n_50, protected_in[13], 1'b1);
  xnor g16 (n_51, protected_in[14], 1'b0);
  xnor g17 (n_52, protected_in[15], 1'b1);
  nand g18 (n_53, n_37, n_38, n_39, n_40);
  nand g19 (n_54, n_41, n_42, n_43, n_44);
  nand g20 (n_55, n_45, n_46, n_47, n_48);
  nand g21 (n_56, n_49, n_50, n_51, n_52);
  nor g22 (n_19, n_53, n_54, n_55, n_56);
  nand \genblk1.dut_NAND2_19  (\genblk1.dut_N154 , \genblk1.dut_N118 ,
       protected_in[1]);
  nand \genblk1.dut_NAND2_22  (\genblk1.dut_N159 , \genblk1.dut_N122 ,
       protected_in[3]);
  nand \genblk1.dut_NAND2_23  (\genblk1.dut_N162 , \genblk1.dut_N126 ,
       protected_in[5]);
  nand \genblk1.dut_NAND2_24  (\genblk1.dut_N165 , \genblk1.dut_N130 ,
       protected_in[7]);
  nand \genblk1.dut_NAND2_25  (\genblk1.dut_N168 , \genblk1.dut_N134 ,
       protected_in[9]);
  nand \genblk1.dut_NAND2_26  (\genblk1.dut_N171 , \genblk1.dut_N138 ,
       protected_in[11]);
  nand \genblk1.dut_NAND2_27  (\genblk1.dut_N174 , \genblk1.dut_N142 ,
       protected_in[13]);
  nand \genblk1.dut_NAND2_28  (\genblk1.dut_N177 , \genblk1.dut_N146 ,
       protected_in[15]);
  nand \genblk1.dut_NAND2_29  (\genblk1.dut_N180 , \genblk1.dut_N150 ,
       other_in[1]);
  not \genblk1.dut_NOT1_1  (\genblk1.dut_N118 , protected_in[0]);
  not \genblk1.dut_NOT1_3  (\genblk1.dut_N122 , protected_in[2]);
  not \genblk1.dut_NOT1_5  (\genblk1.dut_N126 , protected_in[4]);
  not \genblk1.dut_NOT1_7  (\genblk1.dut_N130 , protected_in[6]);
  not \genblk1.dut_NOT1_9  (\genblk1.dut_N134 , protected_in[8]);
  not \genblk1.dut_NOT1_11  (\genblk1.dut_N138 , protected_in[10]);
  not \genblk1.dut_NOT1_13  (\genblk1.dut_N142 , protected_in[12]);
  not \genblk1.dut_NOT1_15  (\genblk1.dut_N146 , protected_in[14]);
  not \genblk1.dut_NOT1_17  (\genblk1.dut_N150 , other_in[0]);
  not \genblk1.dut_NOT1_47  (f_out, \genblk1.dut_N199 );
  and \genblk1.dut_g1  (\genblk1.dut_n_44 , \genblk1.dut_N154 ,
       \genblk1.dut_N159 , \genblk1.dut_N162 );
  and \genblk1.dut_g2  (\genblk1.dut_n_45 , \genblk1.dut_N165 ,
       \genblk1.dut_N168 );
  and \genblk1.dut_g3  (\genblk1.dut_n_46 , \genblk1.dut_N171 ,
       \genblk1.dut_N174 );
  and \genblk1.dut_g4  (\genblk1.dut_n_47 , \genblk1.dut_N177 ,
       \genblk1.dut_N180 );
  and \genblk1.dut_g5  (\genblk1.dut_N199 , \genblk1.dut_n_44 ,
       \genblk1.dut_n_45 , \genblk1.dut_n_46 , \genblk1.dut_n_47 );
endmodule

